### ISSUE TITLE
Getting to work

### ISSUE THREAD

**Issue by mkosler** [HaxePunk/HaxePunk-UI#1]
In order to get this to compile, I needed to move the assignment of defaultSkin into new(), rather than at the static variable declaration. Hopefully, this is obvious as to what to do, but if not, I'll get a diff or make a fork or something.

**Comment by bendmorris** [comment]
Old issue, but this change has been made in the dev branch. As far as I can tell, creating the skin in the static variable declaration had a possibility of triggering an openfl.Assets call while openfl.Assets' own static variables hadn't yet been initialized.
