### ISSUE TITLE
Text not appearing

### ISSUE THREAD

**Issue by mkosler** [HaxePunk/HaxePunk-UI#2]
I can get the almost all of the UI elements to appear, but the Label text isn't appearing. It's even intrinsic to the Label object itself, as no text appears even when I simply create a label. Here is my code:

```
package worlds;

import com.haxepunk.World;
import com.haxepunk.ui.Button;
import com.haxepunk.ui.Label;
import com.haxepunk.ui.TextArea;
import com.haxepunk.ui.TextField;
import com.haxepunk.ui.ToggleButton;

class UITest extends World 
{
    public function new()
    {
        super();

        add(new Button(10, 10, "Press me", 100, 25));
        add(new ToggleButton(10, 40, "Toggle me", 100, 25, false));
        add(new Label("Read me", 125, 10, 200, 200));
        add(new TextField(125, 40, 200, "Write something"));
        add(new TextArea(330, 10, 300, 228, "You could write a book here!"));
    }
}
```

_Note: I added the UI module to my local HaxePunk in com.haxepunk.ui._

**Comment by andyli** [comment]
I'm also getting this issue.

Seriously what is the status of this project? 
Seem like it is not in sync with [punk.ui](https://github.com/RichardMarks/punk.ui).

**Comment by MattTuttle** [comment]
I started working on this before punk.ui really took off. Several of the controls I coded myself so they probably don't match at all. Feel free to make whatever changes you need to it or scrap it and port the current punk.ui.

**Comment by andyli** [comment]
I see. Are you going to keep maintaining/developing this?
The project is extremely handy if it is completed ;)

**Comment by MattTuttle** [comment]
It may be something I work on if I have a project that needs a complex ui. I might be better off rewriting bits of it at some point but for now it will remain dormant.

**Comment by bendmorris** [comment]
The current punk.ui (which seems to have stalled) has been re-ported with some additions and is available in the dev branch. The original is available in the legacy branch.
