### ISSUE TITLE
Error building demo

### ISSUE THREAD

**Issue by wselken** [HaxePunk/HaxePunk-UI#4]
Pulled latest from git and I'm getting the error: "Type not found : com.haxepunk.ui.String" no line number or filed referenced. just an error building.

**Comment by bendmorris** [comment]
I'm seeing an error in lime:

```
/usr/lib/haxe/lib/lime/3,4,1/lime/net/curl/CURL.hx:5: characters 2-7 : Type not found : com.haxepunk.ui.String
```

Just pushed a commit to HaxePunk dev which resolved this for me.

**Comment by wselken** [comment]
This Fixed my issue. Thanks for you help.
